backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}          
      - file: "src/pages/about/index.md"
        label: "About Section"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/skills/index.md"
        label: "Skills Section"
        name: "skills"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "skills"}
          - {label: Subheading, name: subheading, widget: string}
          - {
            label: "Skills",
            name: "skillItems",
            widget: "list",
            fields:
              [
                { label: "Skill Name", name: "skillName", widget: "string" },
              ],
          }
      - file: "src/pages/experiences/index.md"
        label: "Experiences Section"
        name: "experiences"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "experiences"}
          - {label: Subheading, name: subheading, widget: string}
          - {
            label: "Experiences",
            name: "experienceItems",
            widget: "list",
            fields:
              [
                { 
                  label: "Experience", 
                  name: "experience", 
                  widget: "object",
                  fields:
                    [
                      { label: "Title", name: "title", widget: "string" },
                      { label: "Company", name: "company", widget: "string" },
                      { label: "Location", name: "location", widget: "string" },
                      { label: "Company Website", name: "companyWebsite", widget: "string" },
                      { label: "Starting Date", name: "startingDate", widget: "date", date_format: "MMM,YYYY" },
                      { label: "Ending Date", name: "endingDate", widget: "date", date_format: "MMM,YYYY" },
                      { 
                        label: "Duties, Responsibilities, Achievements", 
                        name: "duties", 
                        widget: "list",
                        hint: "There is no limit to number of duties, responsibilities, or achievements per experience. However, it's best to add up to 5.",
                        fields:
                          [
                            { label: "Duty, Responsibility, or Achievment", name: "duty", widget: "string"}
                          ],
                      },    
                    ] 
                },
              ],
          }
      - file: "src/pages/projects/index.md"
        label: "Projects Section"
        name: "projects"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projects"}
          - {label: Subheading, name: subheading, widget: string}
          - {
            label: "Projects",
            name: "projectsItems",
            widget: "list",
            fields:
              [
                { 
                  label: "Project", 
                  name: "project", 
                  widget: "object",
                  fields:
                    [
                      { label: "Project Title", name: "title", widget: "string" },
                      { label: "Project Image", name: "image", widget: "image", hint: "Using a gif can quickly show how the project works." },
                      { label: "Github Link", name: "githubLink", widget: "string", required: false },
                      { label: "External Link", name: "externalLink", widget: "string", required: false, hint: "An exeternal link can be the address to the project's webiste if it is hosted on the internet for example." },                      
                      { label: "Project Description", name: "description", widget: "string" },
                      { 
                        label: "Technologies used for this project", 
                        name: "technologies", 
                        widget: "list",
                        hint: "There is no limit to number of technologies per project. However, it's best to add the core technologies or the ones that were used the most.",
                        fields:
                          [
                            { label: "Technology", name: "technology", widget: "string"}
                          ],
                      },    
                    ] 
                },
              ],
          }

  - name: "navbar"
    label: "Navbar"
    files:
      - file: "src/pages/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
          - { 
              label: "Image for Logo and Tagline", 
              name: "logoImage", 
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },  
                ],
            }
  - name: "footer"
    label: "Footer"
    files:
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "Email",
              name: "email",
              widget: "object",
              fields:
                [
                  { label: Email", name: "email", widget: "string" },
                  { label: "Alternate Email", name: "emailAlt", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }
